package com.tus.model;

import java.io.Serializable;

public abstract class Game implements Serializable {
    // to ensure no errors happen if autogenerated serialVersionUID is different the serialVersionUID procided by the server
    private static final long serialVersionUID = -3903932156551825601L;
    private String name;
    protected String uniqueName;
    protected int numOfPlayers;
    protected boolean isCardGame;

    public Game(String uniqueName, int numOfPlayers, boolean isCardGame) {
        this.uniqueName = uniqueName;
        this.numOfPlayers = numOfPlayers;
        this.isCardGame = isCardGame;
    }

    public String getUniqueName() {
        return uniqueName;
    }

    public void setUniqueName(String uniqueName) {
        this.uniqueName = uniqueName;
    }

    public int getNumOfPlayers() {
        return numOfPlayers;
    }

    public void setNumOfPlayers(int numOfPlayers) {
        this.numOfPlayers = numOfPlayers;
    }

    public boolean isCardGame() {
        return isCardGame;
    }

    public void setCardGame(boolean cardGame) {
        isCardGame = cardGame;
    }


    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    /**
     * Defines some rules and number of players.
     * Outputs it to the console window
     */
    public abstract void createGame();

    @Override
    public String toString() {
        return "Game{" +
                "name='" + uniqueName + '\'' +
                ", numOfPlayers=" + numOfPlayers +
                ", isCardGame=" + isCardGame +
                '}';
    }

}
