package com.tus.model;

import java.io.Serializable;

public abstract class Game implements Serializable {
    // to ensure no errors happen if autogenerated serialVersionUID would
    // be different from the serialVersionUID provided by the server
    private static final long serialVersionUID = -3903932156551825601L;
    private String gameType;        // can be Chess, Checkers, Pocker or Uno
    protected String personalName;  // For example "Uno with friends"
    protected int numOfPlayers;
    protected boolean isCardGame;

    public Game(String personalName, int numOfPlayers, boolean isCardGame) {
        this.personalName = personalName;
        this.numOfPlayers = numOfPlayers;
        this.isCardGame = isCardGame;
    }

    public String getPersonalName() {
        return personalName;
    }

    public void setPersonalName(String personalName) {
        this.personalName = personalName;
    }

    public int getNumOfPlayers() {
        return numOfPlayers;
    }

    public void setNumOfPlayers(int numOfPlayers) {
        this.numOfPlayers = numOfPlayers;
    }

    public boolean isCardGame() {
        return isCardGame;
    }

    public void setCardGame(boolean cardGame) {
        isCardGame = cardGame;
    }

    public String getGameType() {
        return gameType;
    }

    public void setGameType(String gameType) {
        this.gameType = gameType;
    }

    /**
     * Defines some rules and number of players.
     * Outputs it to the console window
     */
    public abstract String createGame();

    @Override
    public String toString() {
        return "Game{" +
                "name='" + personalName + '\'' +
                ", numOfPlayers=" + numOfPlayers +
                ", isCardGame=" + isCardGame +
                '}';
    }

}
